<?php

	include('RSA_base.php');
	include('AES_base.php');


	// ===================== Retrieve the RSA private key generated by RSA_public_key.php =====================
		// Start the session
		session_start();

		// Retrieve the RSA private key saved in current session
		$RSA_private_key = $_SESSION['RSA_private_key'];
	// ===================== ============================================================ =====================
	

	// ===================== Retreive JSON-encoded AES components =====================
		// Retrieve the JSON-encoded encrypted AES Initial Vector
		$JSON_AES_encrypted_IV = $_POST['AES_encrypted_IV'];

		// Retrieve the JSON-encoded encrypted AES key
		$JSON_AES_encrypted_key = $_POST['AES_encrypted_key'];
	// ===================== ==================================== =====================


	// ===================== JSON decode AES components =====================
		// JSON decode encrypted AES Initial Vector
		$AES_encrypted_IV = json_decode($JSON_AES_encrypted_IV);

		// JSON decode encrypted AES key
		$AES_encrypted_key = json_decode($JSON_AES_encrypted_key);
	// ===================== ========================== =====================


	// ===================== RSA decrypt AES components =====================
		// Decrypt the RSA encrypted AES IV
		$AES_IV = RSA_decrypt_string($AES_encrypted_IV, $RSA_private_key);

		// Decrypt the RSA encrypted AES key
		$AES_key = RSA_decrypt_string($AES_encrypted_key, $RSA_private_key);
	// ===================== ========================== =====================


	// ===================== Share through sessions plain AES components =====================
		// Group plain AES components in a AES_components object
		$AES_components = new AES_components($AES_IV, $AES_key);

		// Share AES components using sessions
		$_SESSION['AES_components'] = $AES_components;
	// ===================== =========================================== =====================

?>
